project:
  type: book

book:
  title: "Erfassen von Geodaten im Feld mit [qfield]{.q} und [qfield]{.q} Cloud"
  date: "5/20/2025"
  chapters:
    - index.qmd
    - installation.qmd
    - projekt.qmd
    - synchronisierung.qmd
    - qfield-cloud-management.qmd
    - part: Anhang
      chapters:
      - anhang-1.qmd
      - anhang-2.qmd

bibliography: references.bib
lang: de
format: 
  html: 
    toc: true
    css: style.css
    number-depth: 2
    mermaid:
      theme: neutral




