


## Anhang 1 {.appendix}


| Data Type             | Size and Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|:----------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| INTEGER 32 bit             | 32-bit signed two’s complement integer. Stored as SQLite INTEGER with values in the range [-2147483648, 2147483647].                                                                                                                                                                                                                                                                                                                                                                                                     |
| INTEGER 64 bit         | 64-bit  signed two’s complement integer. Stored as SQLite INTEGER with values  in the range [-9223372036854775808, 9223372036854775807].                                                                                                                                                                                                                                                                                                                                                                                 |
| REAL          | 64-bit IEEE floating point number. Stored as SQLite REAL.                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| TEXT{(maxchar_count)} | Variable length string encoded in either UTF-8 or UTF-16. The optional maxchar_count defines the maximum number of characters in  the string. If not specified, the length is unbounded. Stored as  SQLite TEXT. |
| BLOB{(max_size)}      | Variable  length binary data. The optional max_size defines the maximum number of  bytes in the blob. If not specified, the length is unbounded.                                                                                                                                                                                                        |
| DATE                  | ISO 8601 date string in the form YYYY-MM-DD encoded in either UTF-8 or UTF-16. Stored as SQLite TEXT (see TEXT above).                                                                                                                                                                                                                                                                                                                                                                                             |
| DATETIME              | ISO-8601  date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator  character and Z suffix for coordinated universal time (UTC) encoded in  either UTF-8 or UTF-16. Stored as SQLite TEXT (see TEXT above).                                                                                                                                                                                                                                                                                                |
: Geopackage Data Types. Quelle: [geopackage.org](https://www.geopackage.org/spec140/index.html) {#tbl-geopackage-datatypes}
